version: "3.9"

services:
  db:
    image: postgres:15-alpine
    restart: unless-stopped
    environment:
      POSTGRES_USER:     rxflow
      POSTGRES_PASSWORD: rxflow
      POSTGRES_DB:       rxflow
    ports:
      - "5430:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./backend/app/db/schema.sql:/docker-entrypoint-initdb.d/01_schema.sql

  api:
    build:
      context: ./backend
      dockerfile: Dockerfile
    restart: unless-stopped
    depends_on:
      - db
    environment:
      DATABASE_URL: postgresql+asyncpg://rxflow:rxflow@db:5432/rxflow
    ports:
      - "8001:8001"
    volumes:
      - ./backend:/app
    command: uvicorn app.main:app --host 0.0.0.0 --port 8001 --reload

volumes:
  pgdata:
